
tasks:
  - before: sdk install java 22.3.r17-nik < /dev/null
  - init: ./gradlew build

vscode:
  extensions:
    - DavidAnson.vscode-markdownlintpod/gitpod-yaml)
    - Pivotal.vscode-boot-dev-pack# and commit this file to your remote git repository to share the goodness with others.